### ISSUE TITLE
[Question] Any reasons why RabbitMQ was chosen over other queue technologies?

### ISSUE THREAD

**Issue by simkimsia** [FriendsOfCake/process-mq#2]
Hi there, 

I am new to queue technologies.

Any reasons why RabbitMQ chosen over other queue technologies such as ZeroMQ or BeanstalkD?

**Comment by lorenzo** [comment]
no reason in particular. It is just really really good at being a queue

**Comment by josegonzalez** [comment]
What @lorenzo said. It's actually also quite different from many other queuing systems, so if I were you, I'd look into how each of them work before making a decision (I'm pro RabbitMQ).
